/**
 * Reusable API parameter docs (original English name + bilingual labels/explanations).
 */

export interface ApiDocParam {
  /** Identifier as written in code. */
  name: string
  type?: string
  optional?: boolean
  /** Short human label (locale-specific rendering adds `name` in backticks). */
  labelEn: string
  labelDe: string
  en: string
  de: string
}

export function paramLabel(locale: 'en' | 'de', p: ApiDocParam): string {
  const label = locale === 'de' ? p.labelDe : p.labelEn
  return `${label} (\`${p.name}\`)`
}

/** Shared parameter definitions — compose into method rows. */
export const API_PARAMS = {
  input: {
    name: 'input',
    type: 'TransformInput',
    labelEn: 'Input snapshot',
    labelDe: 'Eingabedaten',
    en: 'Pose, velocity, actions, environment, and optional target for this frame.',
    de: 'Position, Geschwindigkeit, Steuerwerte, Umgebung und optional ein Bewegungsziel in diesem Schritt.',
  },
  dt: {
    name: 'dt',
    type: 'number',
    labelEn: 'Timestep',
    labelDe: 'Zeitschritt',
    en: 'Duration of this physics step in seconds; add to state for timers.',
    de: 'Dauer eines Simulationsschritts in Sekunden; für Timer in state addieren.',
  },
  params: {
    name: 'params',
    type: 'Record<string, unknown>',
    labelEn: 'Config parameters',
    labelDe: 'Einstellungen',
    en: 'JSON values from the transformer row (numbers, booleans, nested objects).',
    de: 'Zahlen und Schalter aus der Transformer-Konfiguration (JSON).',
  },
  state: {
    name: 'state',
    type: 'Record<string, unknown>',
    labelEn: 'Persistent state',
    labelDe: 'Zwischenspeicher',
    en: 'Mutable object kept between frames until the transformer is rebuilt.',
    de: 'Speicher zwischen den Schritten, bis der Transformer neu geladen wird.',
  },
  api: {
    name: 'api',
    type: 'TransformerRuntimeApi',
    labelEn: 'Runtime helpers',
    labelDe: 'Hilfsfunktionen',
    en: 'Frozen helper object: vectors, raycasts, world queries, clamp, log, visualize.',
    de: 'Fertige Funktionen: Vektoren, Strahlen, Abfragen, clamp, log, visualize.',
  },
  a: {
    name: 'a',
    type: 'Vec3',
    labelEn: 'First vector',
    labelDe: 'Erster Vektor',
    en: 'First `[x, y, z]` tuple.',
    de: 'Erstes Tupel `[x, y, z]`.',
  },
  b: {
    name: 'b',
    type: 'Vec3',
    labelEn: 'Second vector',
    labelDe: 'Zweiter Vektor',
    en: 'Second `[x, y, z]` tuple.',
    de: 'Zweites Tupel `[x, y, z]`.',
  },
  v: {
    name: 'v',
    type: 'Vec3',
    labelEn: 'Vector',
    labelDe: 'Vektor',
    en: '`[x, y, z]` tuple.',
    de: 'Tupel `[x, y, z]`.',
  },
  s: {
    name: 's',
    type: 'number',
    labelEn: 'Scalar',
    labelDe: 'Skalar',
    en: 'Number to multiply each component by.',
    de: 'Zahl, mit der jede Komponente multipliziert wird.',
  },
  rotation: {
    name: 'rotation',
    type: 'Rotation',
    labelEn: 'Orientation',
    labelDe: 'Ausrichtung',
    en: 'Euler angles `[x, y, z]` in radians.',
    de: 'Euler-Winkel `[x, y, z]` in Radiant.',
  },
  velocity: {
    name: 'velocity',
    type: 'Vec3',
    labelEn: 'Velocity',
    labelDe: 'Geschwindigkeit',
    en: 'World linear velocity in m/s.',
    de: 'Lineare Geschwindigkeit in m/s.',
  },
  forward: {
    name: 'forward',
    type: 'Vec3',
    labelEn: 'Forward direction',
    labelDe: 'Vorwärts-Richtung',
    en: 'Direction vector; unit length gives stable dot/speed results.',
    de: 'Richtungsvektor; Einheitslänge liefert stabile Skalarprodukte/Geschwindigkeit.',
  },
  vec: {
    name: 'vec',
    type: 'Vec3',
    labelEn: 'Vector',
    labelDe: 'Vektor',
    en: 'Input vector to project or rotate.',
    de: 'Eingabevektor zum Projizieren oder Drehen.',
  },
  planeNormal: {
    name: 'planeNormal',
    type: 'Vec3',
    labelEn: 'Plane normal',
    labelDe: 'Ebenen-Normale',
    en: 'Normal of the plane to project onto (e.g. entity up or `[0, 1, 0]`).',
    de: 'Normale der Ebene (z. B. Oben-Richtung des Objekts oder `[0, 1, 0]`).',
  },
  axis: {
    name: 'axis',
    type: 'Vec3',
    labelEn: 'Rotation axis',
    labelDe: 'Drehachse',
    en: 'Axis to rotate around (often entity up).',
    de: 'Achse zum Drehen (oft die Oben-Richtung des Objekts).',
  },
  angle: {
    name: 'angle',
    type: 'number',
    labelEn: 'Angle',
    labelDe: 'Winkel',
    en: 'Rotation amount in radians.',
    de: 'Drehwinkel in Radiant.',
  },
  angleRad: {
    name: 'angleRad',
    type: 'number',
    labelEn: 'Angle',
    labelDe: 'Winkel',
    en: 'Turn amount in radians.',
    de: 'Drehwinkel in Radiant.',
  },
  from: {
    name: 'from',
    type: 'Vec3',
    labelEn: 'From direction',
    labelDe: 'Ausgangsrichtung',
    en: 'Start direction; normalize for stable angles.',
    de: 'Start-Richtung; normalisieren für stabile Winkel.',
  },
  to: {
    name: 'to',
    type: 'Vec3',
    labelEn: 'To direction',
    labelDe: 'Zielrichtung',
    en: 'Target direction; normalize for stable angles.',
    de: 'Ziel-Richtung; normalisieren für stabile Winkel.',
  },
  origin: {
    name: 'origin',
    type: 'Vec3',
    labelEn: 'Origin',
    labelDe: 'Startpunkt',
    en: 'World-space start point `[x, y, z]`.',
    de: 'Startpunkt in Weltkoordinaten `[x, y, z]`.',
  },
  direction: {
    name: 'direction',
    type: 'Vec3',
    labelEn: 'Direction',
    labelDe: 'Richtung',
    en: 'Ray or offset direction (need not be normalized).',
    de: 'Strahl- oder Versatz-Richtung (muss nicht normalisiert sein).',
  },
  distance: {
    name: 'distance',
    type: 'number',
    labelEn: 'Distance',
    labelDe: 'Abstand',
    en: 'Length in metres along the direction.',
    de: 'Länge in Metern entlang der Richtung.',
  },
  upHint: {
    name: 'upHint',
    type: 'Vec3',
    optional: true,
    labelEn: 'Up hint',
    labelDe: 'Referenz nach oben',
    en: 'Reference up vector; default world +Y `[0, 1, 0]`.',
    de: 'Referenz für „oben“; Standard Welt +Y `[0, 1, 0]`.',
  },
  name: {
    name: 'name',
    type: 'string',
    labelEn: 'Action name',
    labelDe: 'Name der Steuerung',
    en: 'Key in `input.actions` (e.g. `"throttle"`).',
    de: 'Schlüssel in `input.actions` (z. B. `"throttle"` für Gas).',
  },
  overlayName: {
    name: 'name',
    type: 'string',
    labelEn: 'Overlay label',
    labelDe: 'Beschriftung',
    en: 'Short label beside the bar (drawn in white).',
    de: 'Kurze Beschriftung neben dem Balken (weiß gezeichnet).',
  },
  value: {
    name: 'value',
    type: 'number',
    labelEn: 'Value',
    labelDe: 'Wert',
    en: 'Number to clamp.',
    de: 'Zahl, die begrenzt werden soll.',
  },
  numericValue: {
    name: 'value',
    type: 'number',
    labelEn: 'Numeric value',
    labelDe: 'Zahl',
    en: 'Finite number to show on the overlay.',
    de: 'Endliche Zahl für das Overlay.',
  },
  min: {
    name: 'min',
    type: 'number',
    labelEn: 'Minimum',
    labelDe: 'Minimum',
    en: 'Lower bound (inclusive).',
    de: 'Untere Grenze (inklusive).',
  },
  max: {
    name: 'max',
    type: 'number',
    labelEn: 'Maximum',
    labelDe: 'Maximum',
    en: 'Upper bound (inclusive).',
    de: 'Obere Grenze (inklusive).',
  },
  maxDistance: {
    name: 'maxDistance',
    type: 'number',
    optional: true,
    labelEn: 'Max distance',
    labelDe: 'Maximale Reichweite',
    en: 'Ray length in metres.',
    de: 'Strahllänge in Metern.',
  },
  spreadWidth: {
    name: 'spreadWidth',
    type: 'number',
    labelEn: 'Spread width',
    labelDe: 'Streubreite',
    en: 'Total sideways span in metres (rays from −width/2 to +width/2).',
    de: 'Gesamtbreite seitlich in Metern (Strahlen von −width/2 bis +width/2).',
  },
  rayCount: {
    name: 'rayCount',
    type: 'number',
    labelEn: 'Ray count',
    labelDe: 'Strahl-Anzahl',
    en: 'Number of parallel rays (integer ≥ 1, includes center).',
    de: 'Anzahl paralleler Strahlen (Ganzzahl ≥ 1, inkl. Mitte).',
  },
  options: {
    name: 'options',
    type: '{ visualize?, hitColor?, missColor? }',
    optional: true,
    labelEn: 'Options',
    labelDe: 'Optionen',
    en: 'Optional debug draw in Builder Visualize mode.',
    de: 'Optionale Debug-Linien im Builder (Visualize-Modus).',
  },
  id: {
    name: 'id',
    type: 'string',
    labelEn: 'Entity id',
    labelDe: 'Objekt-ID',
    en: 'World id of another entity.',
    de: 'ID eines anderen Objekts in der Welt.',
  },
  message: {
    name: 'message',
    type: 'string',
    labelEn: 'Message',
    labelDe: 'Nachricht',
    en: 'Text shown in Play-mode snackbar.',
    de: 'Text, der beim Spielen kurz eingeblendet wird.',
  },
  durationSeconds: {
    name: 'durationSeconds',
    type: 'number',
    optional: true,
    labelEn: 'Duration',
    labelDe: 'Anzeigedauer',
    en: 'How long the message stays visible (default 4 s).',
    de: 'Wie lange die Meldung sichtbar bleibt (Standard 4 s).',
  },
  color: {
    name: 'color',
    type: 'string',
    labelEn: 'Color',
    labelDe: 'Farbe',
    en: 'CSS color string (e.g. `"red"`, `"#00ff00"`).',
    de: 'CSS-Farbstring (z. B. `"red"`, `"#00ff00"`).',
  },
  index: {
    name: 'index',
    type: 'number',
    labelEn: 'Overlay slot',
    labelDe: 'Anzeige-Slot',
    en: 'Variable overlay channel, integer 1–16.',
    de: 'Kanal für die Zahlen-Anzeige, Ganzzahl von 1 bis 16.',
  },
  fromPoint: {
    name: 'from',
    type: 'Vec3',
    labelEn: 'From point',
    labelDe: 'Startpunkt',
    en: 'Line start in world space.',
    de: 'Linienstart in Weltkoordinaten.',
  },
  toPoint: {
    name: 'to',
    type: 'Vec3',
    labelEn: 'To point',
    labelDe: 'Endpunkt',
    en: 'Line end in world space.',
    de: 'Linienende in Weltkoordinaten.',
  },
} satisfies Record<string, ApiDocParam>

export const TRANSFORM_FUNCTION_PARAMS: ApiDocParam[] = [
  API_PARAMS.input,
  API_PARAMS.dt,
  API_PARAMS.params,
  API_PARAMS.state,
  API_PARAMS.api,
]
